/* LOCATION */
export const LOCATION_LIST = 'LOCATION_LIST';
export const LOCATION_LIST_SUCCESS = 'LOCATION_LIST_SUCCESS';
export const LOCATION_LIST_FAILED = 'LOCATION_LIST_FAILED';

/* LOCATION */
export const LOCATION_DETAILS = 'LOCATION_DETAILS';
export const LOCATION_DETAILS_SUCCESS = 'LOCATION_DETAILS_SUCCESS';
export const LOCATION_DETAILS_FAILED = 'LOCATION_DETAILS_FAILED';

export const COUNTRY_LIST = 'COUNTRY_LIST';
export const COUNTRY_LIST_SUCCESS = 'COUNTRY_LIST_SUCCESS';
export const COUNTRY_LIST_FAILED = 'COUNTRY_LIST_FAILED';

export const CITY_LIST = 'CITY_LIST';
export const CITY_LIST_SUCCESS = 'CITY_LIST_SUCCESS';
export const CITY_LIST_FAILED = 'CITY_LIST_FAILED';
